name: foo
description: foo

runs:
  using: composite
  steps:
    - uses: suzuki-shunsuke/tfaction/get-target-config@main
      id: target-config
    - uses: suzuki-shunsuke/tfaction/get-global-config@main
      id: global-config
    - uses: suzuki-shunsuke/tfaction/check-terraform-skip@main
      id: check-terraform-skip
      with:
        labels: ${{ env.CI_INFO_TEMP_DIR }}/labels.txt
        pr_author: ${{ env.CI_INFO_PR_AUTHOR }}
        skip_label_prefix: ${{ steps.global-config.outputs.label_prefix_skip }}
