---
targets:
- working_directory: aws/
  target: aws/
  aws_region: ap-northeast-1
  assume_role_arns:
    tfmigrate_plan: arn:aws:iam::000000000000:role/GitHubActionsTerraformPR
    terraform_plan: arn:aws:iam::000000000000:role/GitHubActionsTerraformPR
    tfmigrate_apply: arn:aws:iam::000000000000:role/GitHubActionsTerraformMain
    terraform_apply: arn:aws:iam::000000000000:role/GitHubActionsTerraformMain

- working_directory: github/services/
  target: github/
  aws_region: ap-northeast-1
  assume_role_arns:
    tfmigrate_plan: arn:aws:iam::000000000000:role/GitHubActionsTerraformPRGitHub
    terraform_plan: arn:aws:iam::000000000000:role/GitHubActionsTerraformPRGitHub
    tfmigrate_apply: arn:aws:iam::000000000000:role/GitHubActionsTerraformMainGitHub
    terraform_apply: arn:aws:iam::000000000000:role/GitHubActionsTerraformMainGitHub

label_prefixes:
  target: "target:"
  tfmigrate: "migrate:"
  ignore: "ignore:"
