title: Bug Report
labels:
  - bug
body:
  - type: textarea
    id: aqua-version
    attributes:
      label: aqua version
      description: Please use the latest version.
      value: |
        ```console
        $ aqua -v

        ```
      render: bash
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      value: |
        * OS (Windows, Linux, macOS, etc):
        * CPU Architecture (amd64, arm64, etc):
      render: bash
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      value: |
        * aqua.yaml
        * executed command and output

        > aqua.yaml should be not partial but complete configuration.
        > Please remove unneeded configuration to reproduce the issue.

        ```yaml
        # aqua.yaml

        ```

        ```console
        $ 
        ```
      render: bash
    validations:
      required: true
  - type: textarea
    id: debug-output
    attributes:
      label: Debug output
      description: Please set the environment variable `AQUA_LOG_LEVEL=debug` and run aqua and tell us the debug output.
      value: |
        ```console
        $ 
        ```
      render: bash
    validations:
      required: false
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: important-factoid
    attributes:
      label: Important Factoids
      value:
      render: bash
    validations:
      required: false
  - type: textarea
    id: reference
    attributes:
      label: Reference
      value: |
        *
      render: bash
    validations:
      required: false
