issuer: https://token.actions.githubusercontent.com
subject: repo:suzuki-shunsuke/test-github-action-2:ref:refs/heads/test-octo-sts

permissions:
  contents: read
  issues: write

repositories:
  - test-github-action
  - test-github-action-2
