---
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
permissions: {}
jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: echo actionlint
