name: Close issue

on:
  issues:
    types: [opened]

jobs:
  close-issue:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: suzuki-shunsuke/issue-close-lock-action@main
        with:
          issue_number: ${{github.event.issue.number}}
          is_lock: "false"
