name: count the number of asdf plugins
on: workflow_dispatch
jobs:
  count-asdf-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2
      - run: asdf plugin list all | wc -l
