---
name: pinact

on: pull_request

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout private repository
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - uses: aquaproj/aqua-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        with:
          aqua_version: v2.9.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Generate token
        id: generate_token
        if: "! github.event.pull_request.head.repo.fork"
        uses: suzuki-shunsuke/github-token-action@04d633c696e9d09e958c8b815c75db9606d6d927 # v0.2.0
        with:
          github_app_id: ${{secrets.APP_ID}}
          github_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

      - uses: actions/github-script@v6
        id: files
        with:
          script: |
            let output = '';
            const options = {};
            options.listeners = {
              stdout: (data) => {
                output += data.toString();
              },
            };
            await exec.exec('git ls-files .github', options);
            return output;
          result-encoding: string

      - uses: ./.github/actions/pinact
        with:
          github_token: ${{steps.generate_token.outputs.token}}
          files: ${{steps.files.outputs.result}}
