---
name: pull_request_target
on: pull_request_target
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}
      - run: env | grep -E "^GITHUB_"

      - uses: actions/github-script@v6
        id: pr
        with:
          result-encoding: string
          script: |
            await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
      - run: echo "$OUTPUT"
        env:
          OUTPUT: ${{toJSON(steps.pr.outputs)}}

      - uses: actions/github-script@v6
        id: pr2
        with:
          script: |
            await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
      - run: echo "$OUTPUT"
        env:
          OUTPUT: ${{toJSON(steps.pr2.outputs)}}
