---
name: pull_request_target
on: pull_request_target
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJSON(github)}}
      - run: env | grep -E "^GITHUB_"

      - uses: actions/github-script@v6
        id: pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pullRequest
      - run: echo "$OUTPUT"
        env:
          OUTPUT: ${{toJSON(steps.pr.outputs)}}
      - run: echo "$MERGE_COMMIT_SHA"
        env:
          MERGE_COMMIT_SHA: ${{fromJSON(steps.pr.outputs.result).merge_commit_sha}}
