---
name: status-check
on:
  workflow_run:
    workflows: [test]
    types:
      - completed
jobs:
  status-check:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJson(github.event) }}
      - run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$GITHUB_REPOSITORY/check-runs" \
            -f "name=status-check" \
            -f "head_sha=$SHA" \
            -f "status=completed" \
            -f "conclusion=$CONCLUSION"
        env:
          GH_TOKEN: ${{ github.token }}
          SHA: ${{ github.event.workflow_run.head_sha }}
          CONCLUSION: ${{ github.event.workflow_run.conclusion }}

       
