---
name: status-check
on:
  workflow_run:
    workflows: [test]
    types:
      - completed
jobs:
  status-check:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJson(github.event) }}
