---
name: test-pinact
on: workflow_call
jobs:
  integration-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3
      - uses: actions/checkout@v2
      - uses: actions/cache@v3.3.1
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@813a6d08c08cfd7a08618a89a59bfe78e573597c # v1.0.1
    with:
      aqua_version: v2.3.4
    permissions:
      pull-requests: write
      contents: read
