---
name: close pr
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr close -R "$GITHUB_REPOSITORY" -d "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
