name: Synchronize issue description

on:
  issue_comment:
    types:
      - created

jobs:
  sync-issue:
    uses: suzuki-shunsuke/tfaction/.github/workflows/sync-drift-issue-description.yaml@feat/detect-drift
    if: |
      !github.event.issue.pull_request && startsWith(github.event.issue.title, 'Terraform Drift (') && endsWith(github.event.issue.title, ')')
    permissions:
      issues: write
