---
name: wc-test
on: workflow_call
jobs:
  foo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/github-script@v7
        id: metadata
        with:
          result-encoding: string
          script: |
            if (context.eventName.startsWith('pull_request')) {
              return JSON.stringify({
                "pull_request": {
                  "number": context.payload.pull_request.number,
                }
              })
            }
            return {}
      - run: echo ${{ fromJson(steps.metadata.outputs.result).pull_request.number }}
