---
name: wc-test
on: workflow_call
jobs:
  foo:
    runs-on: ubuntu-24.04
    steps:
      - run: touch .github/workflows/yoo.yaml
      - uses: suzuki-shunsuke/commit-action@fix-remove-contents-write-if-only-workflow-is-change
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
