---
name: wc-test
on: workflow_call
jobs:
  foo:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: ${{github.head_ref}}
      - run: echo foo > foo.txt
      - run: git add foo.txt
      - run: git config user.name suzuki-shunsuke
      - run: git config user.email suzuki-shunsuke@users.noreply.github.com
      - run: git commit -m "add foo.txt"
      - run: gh auth setup-git
        env:
          GH_HOST: github.com
      - run: git push origin "$GITHUB_HEAD_REF"
        env:
          GH_TOKEN: ${{github.token}}
  bar:
    runs-on: ubuntu-24.04
    steps:
      - run: test -n "$TEST_ENV"
        env:
          TEST_ENV: ${{vars.TEST_ENV}}

