---
name: wc-test
on: workflow_call
jobs:
  foo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/github-script@v7
        id: metadata
        with:
          script: |
            return context;
            if (context.eventName.startsWith('pull_request')) {
              return {
                "pull_request": {
                  "number": context.payload.pull_request.number,
                }
              }
            }
            return {}
      - run: echo ${CONTEXT}
        env:
          CONTEXT: ${{ steps.metadata.outputs.result }}
      - run: echo ${{ fromJson(steps.metadata.outputs.result).payload.pull_request.number }}
        if: fromJson(steps.metadata.outputs.result).payload.pull_request
