---
name: wc-test
on: workflow_call
jobs:
  foo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/github-script@v7
        id: metadata
        with:
          script: |
            return {
              context: context,
            };
      - run: echo ${CONTEXT}
        env:
          CONTEXT: ${{ steps.metadata.outputs.result }}
      - run: echo ${{ fromJson(steps.metadata.outputs.result).context.payload.pull_request.number }}
        if: fromJson(steps.metadata.outputs.result).context.payload.pull_request
