---
name: wc-test
on: workflow_call
jobs:
  foo:
    runs-on: ubuntu-24.04
    steps:
      - run: test -n "$TEST_ENV"
        env:
          TEST_ENV: ${{vars.TEST_ENV}}
  bar:
    runs-on: ubuntu-24.04
    steps:
      - run: test -n "$TEST_ENV"
        env:
          TEST_ENV: ${{vars.TEST_ENV}}

