---
name: test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: aquaproj/aqua-installer@v2.1.1
        with:
          aqua_version: v2.3.6
      - run: tflint -v
      - run: |
          tflint --format json --module '.' |
            reviewdog \
              -f rdjson \
              -name tflint \
              -filter-mode nofilter \
              -reporter github-check \
              -level warning \
              -fail-on-error 1
      - run: tflint
